# https://github.com/maximecb/gym-minigrid

environment:
  type: "Minigrid"
  name: "MiniGrid-MemoryS9-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  resize_vis_obs: [84, 84]
  reset_params:
    start-seed: 0
    num-seeds: 100
    view-size: 3
    max-episode-steps: 96

model:
  load_model: False
  model_path: "./models/minigrid_S17-199.pt"
  checkpoint_interval: 100
  activation: "relu"
  vis_encoder: "cnn"
  vec_encoder_layer: "linear"
  num_vec_encoder_units: 128
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 512
  recurrence:
    layer_type: "lstm"
    num_layers: 1
    sequence_length: 8
    hidden_state_size: 256
    hidden_state_init: "zero"
    reset_hidden_state: False
    residual: False

evaluation:
  evaluate: False
  n_workers: 3
  seeds:
    start-seed: 100000
    num-seeds: 10
  interval: 100

sampler:
  n_workers: 16
  worker_steps: 256

trainer:
  algorithm: "DecoupledPPO"
  resume_at: 0
  gamma: 0.99
  lamda: 0.95
  updates: 500
  policy_epochs: 4
  n_policy_mini_batches: 8
  advantage_normalization: "minibatch"
  value_epochs: 4
  n_value_mini_batches: 8
  refresh_buffer_epoch: -1
  value_update_interval: 1
  max_policy_grad_norm: 0.5
  max_value_grad_norm: 0.5
  run_threaded: True
  policy_learning_rate_schedule:
    initial: 2.0e-4
    final: 2.0e-4
    power: 1.0
    max_decay_steps: 500
  value_learning_rate_schedule:
    initial: 2.0e-4
    final: 2.0e-4
    power: 1.0
    max_decay_steps: 500
  beta_schedule:
    initial: 0.001
    final: 0.0001
    power: 1.0
    max_decay_steps: 500
  policy_clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 500
  value_clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 500