environment:
  type: "MemoryGym"
  name: "MortarMayhem-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  positional_endocing: False
  resize_vis_obs: [84, 84]
  reset_params:
    start-seed: 0
    num-seeds: 100000
    agent_scale: 0.25
    arena_size: 5
    allowed_commands: 9
    command_count: [10]
    explosion_duration: [6]
    explosion_delay: [18]
    reward_command_failure: 0.0
    reward_command_success: 0.1
    reward_episode_success: 0.0

model:
  load_model: False
  model_path: "./trxl-10000.pt"
  checkpoint_interval: 500
  activation: "relu"
  vis_encoder: "cnn"
  vec_encoder_layer: "linear"
  num_vec_encoder_units: 128
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 384
  transformer:
    num_blocks: 3
    embed_dim: 384
    num_heads: 4
    memory_length: 275
    positional_encoding: "relative" # options: "" "relative" "learned"
    layer_norm: "pre" # options: "", "pre", "post"
    init_weights: "xavier" # options: "xavier" "orthogonal" "tfixup" "kaiming"
    gtrxl: False
    gtrxl_bias: 0.0
    gtrxl_swap: False
  obs_decoder:
    # Whether to attach the decoder to the cnn or the memory
    attach_to: "memory" # "memory"
    # Whether to detach the input to the decoder from the computational graph
    detach_gradient: True

sampler:
  n_workers: 16
  worker_steps: 256

trainer:
  algorithm: "DecoderTrainer"
  resume_at: 0
  updates: 30
  epochs: 1
  n_mini_batches: 8
  max_grad_norm: 1.0
  learning_rate_schedule:
    initial: 0.001
    final: 0.00001
    power: 1.0
    max_decay_steps: 100