environment:
  type: "MemoryGym"
  name: "Endless-MysteryPath-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  positional_endocing: False
  resize_vis_obs: [84, 84]
  reset_params:
    start-seed: 0
    num-seeds: 100000
    max_steps: 1024
    agent_scale: 0.25
    agent_speed: 3.0
    show_origin: True
    show_past_path: True
    show_background: False
    show_stamina: False
    visual_feedback: True
    camera_offset_scale: 5.0
    stamina_level: 20
    reward_fall_off: 0.0
    reward_path_progress: 0.1
    reward_step: 0.0

model:
  load_model: False
  model_path: "./checkpoints/mg_17r/20220112-065616_2/mg_17r-208.pt"
  checkpoint_interval: 500
  activation: "relu"
  vis_encoder: "cnn"
  vec_encoder_layer: "linear"
  num_vec_encoder_units: 128
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 384
  transformer:
    num_blocks: 3
    embed_dim: 384
    num_heads: 4
    memory_length: 256
    positional_encoding: "relative" # options: "" "relative" "learned"
    layer_norm: "pre" # options: "", "pre", "post"
    init_weights: "xavier" # options: "xavier" "orthogonal" "tfixup" "kaiming"
    gtrxl: False
    gtrxl_bias: 0.0
    gtrxl_swap: False

evaluation:
  evaluate: False
  n_workers: 5
  seeds:
    start-seed: 100000
    num-seeds: 50
  interval: 100

sampler:
  n_workers: 32
  worker_steps: 512

trainer:
  algorithm: "PPO"
  resume_at: 0
  gamma: 0.995
  lamda: 0.95
  updates: 30000
  epochs: 3
  refresh_buffer_epoch: -1
  n_mini_batches: 8
  value_coefficient: 0.5
  advantage_normalization: "no"
  max_grad_norm: 0.25
  share_parameters: True
  learning_rate_schedule:
    initial: 2.75e-4
    final: 1.0e-5
    power: 1.0
    max_decay_steps: 10000
  beta_schedule:
    initial: 0.0001
    final: 0.000001
    power: 1.0
    max_decay_steps: 10000
  clip_range_schedule:
    initial: 0.1
    final: 0.1
    power: 1.0
    max_decay_steps: 10000