# https://github.com/maximecb/gym-minigrid

environment:
  type: "Minigrid"
  name: "MiniGrid-KeyCorridorS3R1-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  resize_vis_obs: [54, 54]
  reset_params:
    start-seed: 0
    num-seeds: 1000
    # The view size of the agent, which has to be an odd number
    # The default value in minigrid is 7, which is not a good challenge in terms of agent memory
    view-size: 7

model:
  load_model: False
  model_path: "./checkpoints/mg_17r/20220112-065616_2/mg_17r-208.pt"
  checkpoint_interval: 100
  activation: "relu"
  vis_encoder: "cnn"
  vec_encoder_layer: "linear"
  num_vec_encoder_units: 128
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 512
  use_helm: True

evaluation:
  evaluate: False
  n_workers: 3
  seeds: [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010]
  interval: 100

sampler:
  type: "TrajectorySampler"
  n_workers: 16
  worker_steps: 128

trainer:
  algorithm: "PPO"
  resume_at: 0
  gamma: 0.99
  lamda: 0.99
  updates: 245
  epochs: 3
  refresh_buffer_epoch: -1
  n_mini_batches: 8
  value_coefficient: 0.5
  max_grad_norm: 0.5
  share_parameters: True
  learning_rate_schedule:
    initial: 1.0e-4
    final: 1.0e-4
    power: 1.0
    max_decay_steps: 1000
  beta_schedule:
    initial: 0.00001
    final: 0.000001
    power: 1.0
    max_decay_steps: 1000
  clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 1000