environment:
  type: "PokeRedV2"
  name: "./neroRL/environments/poke_red/PokemonRed.gb"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  resize_vis_obs: [72, 80]
  reset_params:
    start-seed: 0
    num-seeds: 1
    initial-state: "./neroRL/environments/poke_red/has_pokedex_nballs.state"
    max-steps: 20

model:
  load_model: False
  model_path: ""
  checkpoint_interval: 200
  activation: "relu"
  vis_encoder: "cnn"
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 512
  modalities:
    screens:
      type: "atari_cnn"
      dtype: "float32"
    map:
      type: "atari_cnn"
      dtype: "float32"
    events:
      type: "fc"
      dtype: "float32"
      dims: [256, 64]
      activation: "relu"
    game_state:
      type: "fc"
      dtype: "float32"
      dims: [64]
      activation: "relu"
  # recurrence:
  #   layer_type: "gru"
  #   num_layers: 1
  #   sequence_length: -1
  #   hidden_state_size: 512
  #   hidden_state_init: "zero"
  #   reset_hidden_state: True
  #   residual: False
  #   embed: True

evaluation:
  evaluate: False
  n_workers: 3
  seeds:
    start-seed: 100000
    num-seeds: 10
  interval: 200

sampler:
  n_workers: 4
  worker_steps: 128

trainer:
  algorithm: "PPO"
  resume_at: 0
  gamma: 0.997
  lamda: 0.95
  updates: 50000
  epochs: 3
  n_mini_batches: 8
  value_coefficient: 0.5
  max_grad_norm: 0.5
  advantage_normalization: "minibatch"
  learning_rate_schedule:
    initial: 3.0e-4
    final: 3.0e-4
    power: 1.0
    max_decay_steps: 50000
  beta_schedule:
    initial: 0.01
    final: 0.0
    power: 1.0
    max_decay_steps: 50000
  clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 50000