# https://github.com/maximecb/gym-minigrid

environment:
  type: "Minigrid"
  name: "MiniGrid-MemoryS9-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  grayscale: False
  resize_vis_obs: [84, 84]
  reset_params:
    start-seed: 0
    num-seeds: 1000
    # The view size of the agent, which has to be an odd number
    # The default value in minigrid is 7, which is not a good challenge in terms of agent memory
    view-size: 3
    max-episode-steps: 128

model:
  load_model: False
  model_path: "./checkpoints/trxl/20230501-101334_2/trxl-499.pt"
  checkpoint_interval: 100
  activation: "relu"
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 384
  modalities:
    vis_obs:
      type: "atari_cnn"
      dtype: "float32"
  transformer:
    num_blocks: 2
    embed_dim: 256
    num_heads: 4
    memory_length: 64
    positional_encoding: "absolute" # options: "" "absolute" "learned"
    add_positional_encoding_to_query: False # Only supported for absolute positional encoding
    layer_norm: "pre" # options: "" "pre" "post"
    init_weights: "xavier" # options: "xavier" "orthogonal" "tfixup" "kaiming"
    gtrxl: False
    gtrxl_bias: 0.0
    gtrxl_swap: False

evaluation:
  evaluate: False
  n_workers: 3
  seeds:
    start-seed: 100000
    num-seeds: 10
  interval: 100

sampler:
  n_workers: 16
  worker_steps: 256

trainer:
  algorithm: "PPO"
  resume_at: 0
  gamma: 0.995
  lamda: 0.95
  updates: 500
  epochs: 3
  n_mini_batches: 8
  advantage_normalization: "no"
  value_coefficient: 0.5
  max_grad_norm: 0.25
  learning_rate_schedule:
    initial: 2.0e-4
    final: 1.0e-5
    power: 1.0
    max_decay_steps: 1000
  beta_schedule:
    initial: 0.0001
    final: 0.000001
    power: 1.0
    max_decay_steps: 1000
  clip_range_schedule:
    initial: 0.1
    final: 0.1
    power: 1.0
    max_decay_steps: 1000